[package]
name = "basic_opengl_window"
version = "0.1.0"
authors = ["richard"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gleam = "0.6"
glutin = "0.21"